# Main build pipeline that verifies, builds, and deploys the software
name: Build and Deploy
# Events that trigger the workflow
on:
  # Trigger based on push to all branches - TODO
  # push:
    # branches:
      # - 'development'
      # - 'feature/**'
      # - 'release/**'
      # - 'main'
    # tags-ignore:
      # - '*'
  # Run workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        venue:
            type: choice
            description: Venue to deploy to
            options:
                - DEV1
                - DEV2
                - OPS

# Environment variables
env:
  APP_NAME_ENV: 'upload'

jobs:
  build:
    name: Build and Deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:

      # DEV1 environment variables
      - name: Set Environment Variables
        if: github.event.inputs.venue == 'DEV1'
        run: |
          echo "TARGET_ENV=DEV1" >> $GITHUB_ENV
          echo "PREFIX_ENV=confluence-dev1" >> $GITHUB_ENV
      
      # DEV2 environment variables
      - name: Set Environment Variables
        if: github.event.inputs.venue == 'DEV2'
        run: |
          echo "TARGET_ENV=DEV2" >> $GITHUB_ENV
          echo "PREFIX_ENV=confluence-dev2" >> $GITHUB_ENV

      # OPS environment variables
      - name: Set Environment Variables
        if: github.event.inputs.venue == 'OPS'
        run: |
          echo "TARGET_ENV=OPS" >> $GITHUB_ENV
          echo "PREFIX_ENV=confluence-ops" >> $GITHUB_ENV

      # Check out GitHub repo
      - uses: actions/checkout@v4

      # SNYK IAC scan and report - TODO
      # - name: Run Snyk IAC to test and report
        # uses: snyk/actions/iac@master
        # env:
            # SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        # with:
          # command: test
          # args: >
              # --org=${{ secrets.SNYK_ORG_ID }}
              # --severity-threshold=high
              # --report

      # SNYK Python
      # - name: Run Snyk Python to test
        # uses: snyk/actions/python-3.10@master
        # env:
            # SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        # with:
          # command: test
          # args: >
              # --org=${{ secrets.SNYK_ORG_ID }}
              # --project-name=${{ github.repository }}
              # --severity-threshold=high
              # --fail-on=all
      # - name: Run Snyk Python to report
        # uses: snyk/actions/python-3.10@master
        # env:
          # SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        # with:
          # command: monitor
          # args: >
            # --org=${{ secrets.SNYK_ORG_ID }}
            # --project-name=${{ github.repository }}

      # Set up Python3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Create Lambda zip deployment
      - name: Create Lambda zip package
        run: deploy/deploy-zip.sh ${APP_NAME_ENV}

      - name: Upload zip package
        uses: actions/upload-artifact@v4
        with:
          name: uploader.zip
          path: uploader.zip


      # Configure credentials 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}', env.TARGET_ENV)] }}
          aws-secret-access-key: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}', env.TARGET_ENV)] }}
          aws-region: us-west-2
          mask-aws-account-id: true

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Define TF_VAR values
        run: |
          echo "TF_VAR_environment=$TARGET_ENV" >> $GITHUB_ENV
          echo "TF_VAR_prefix=$PREFIX_ENV" >> $GITHUB_ENV
          echo "TF_IN_AUTOMATION=true" >> $GITHUB_ENV

      - name: Initialize Terraform
        working-directory: terraform/
        run: |
          terraform init -reconfigure \
              -backend-config="bucket=${PREFIX_ENV}-tf-state" \
              -backend-config="key=${APP_NAME_ENV}.tfstate" \
              -backend-config="region=${AWS_DEFAULT_REGION}"

      - name: Validate Terraform
        working-directory: terraform/
        run: terraform validate -no-color

      # Deploy AWS infrastructure
      - name: Deploy Terraform
        working-directory: terraform/
        run: terraform apply -auto-approve